#!/usr/bin/env python3
"""Generate or check a manifest of generated vendor outputs."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys


REPO_ROOT = Path(__file__).resolve().parents[3]
DIST_ROOT = REPO_ROOT / "dist"
MANIFEST_PATH = DIST_ROOT / "generated-output-manifest.yaml"
GENERATED_RE = re.compile(r"Generated by ([^.]+\.py)\. Do not edit directly\.")
SOURCE_ID_RE = re.compile(r"`((?:rule|skill)\.[a-z0-9.-]+)`")


def rel(path: Path) -> str:
    return str(path.relative_to(REPO_ROOT))


def generated_files() -> list[tuple[Path, str, list[str]]]:
    entries: list[tuple[Path, str, list[str]]] = []
    for path in sorted(DIST_ROOT.rglob("*")):
        if not path.is_file() or path == MANIFEST_PATH:
            continue
        if path.name == ".gitkeep":
            continue
        text = path.read_text(encoding="utf-8")
        match = GENERATED_RE.search(text)
        if match is None:
            continue
        source_ids = sorted(set(SOURCE_ID_RE.findall(text)))
        entries.append((path, match.group(1), source_ids))
    return entries


def render_manifest() -> str:
    lines = [
        "# Generated by core/skills/tools/generated_manifest.py. Do not edit directly.",
        "generated_outputs:",
    ]

    for path, renderer, source_ids in generated_files():
        lines.extend(
            [
                f"  - path: {rel(path)}",
                f"    renderer: {renderer}",
                "    source_ids:",
            ]
        )
        if source_ids:
            for source_id in source_ids:
                lines.append(f"      - {source_id}")
        else:
            lines.append("      - none")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="check manifest freshness")
    args = parser.parse_args()

    rendered = render_manifest()
    if args.check:
        if not MANIFEST_PATH.exists():
            print(f"{rel(MANIFEST_PATH)}: missing generated manifest", file=sys.stderr)
            return 1
        current = MANIFEST_PATH.read_text(encoding="utf-8")
        if current != rendered:
            print(f"{rel(MANIFEST_PATH)}: generated manifest is stale", file=sys.stderr)
            return 1
        print(f"{rel(MANIFEST_PATH)} is up to date")
        return 0

    MANIFEST_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {rel(MANIFEST_PATH)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
