#!/usr/bin/env python3
"""Render canonical content into Devin-oriented generated output."""

from __future__ import annotations

import argparse
from pathlib import Path
import shutil
import sys

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from render_support import (  # noqa: E402
    body_without_title,
    canonical_items,
    generated_header,
    rel,
    skill_name,
    title,
)


REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_ROOT = REPO_ROOT / "dist" / "devin" / "repo-files"
AGENTS_OUTPUT = OUTPUT_ROOT / "AGENTS.md"
AGENTS_SKILLS_OUTPUT = OUTPUT_ROOT / ".agents" / "skills"
DEVIN_CONFIG_OUTPUT = OUTPUT_ROOT / ".devin" / "config.json"
DEVIN_SKILLS_OUTPUT = OUTPUT_ROOT / ".devin" / "skills"
DEVIN_AGENTS_OUTPUT = OUTPUT_ROOT / ".devin" / "agents"
DEVIN_HOOKS_OUTPUT = OUTPUT_ROOT / ".devin" / "hooks.v1.json"
RENDERER = "adapters/devin/render.py"


def render_agents(items) -> str:
    source_ids = ", ".join(f"`{item.item_id}`" for item in sorted(items, key=lambda i: i.item_id))
    return (
        f"{generated_header(RENDERER)}\n\n"
        "# Devin Instructions\n\n"
        "This generated file adapts canonical repository guidance for Devin.\n"
        "Canonical policy and procedure remain in `core/`.\n\n"
        f"Sources: {source_ids}\n\n"
        "Generated product skills are under `.agents/skills/`; generated Devin "
        "for Terminal skills, agents, hooks, and configuration are under `.devin/`.\n"
    )


def render_skill(item) -> str:
    name = skill_name(item.item_id)
    return (
        "---\n"
        f"name: {name}\n"
        f"description: {item.summary}\n"
        f"source_id: {item.item_id}\n"
        "---\n"
        "\n"
        f"{generated_header(RENDERER)}\n"
        "\n"
        f"# {title(item)}\n"
        "\n"
        "Canonical policy and procedure remain in `core/`.\n"
        "\n"
        f"Source: `{item.item_id}`\n"
        "\n"
        f"{body_without_title(item.body)}\n"
    )


def render_config(items) -> str:
    source_ids = [item.item_id for item in sorted(items, key=lambda i: i.item_id)]
    lines = [
        "{",
        '  "_generated": "<!-- Generated by adapters/devin/render.py. Do not edit directly. -->",',
        '  "_canonical_boundary": "Canonical policy and procedure remain in `core/`.",',
        '  "agents": [',
        '    ".devin/agents/canonical-guidance/AGENT.md"',
        "  ],",
        '  "source_ids": [',
    ]
    for index, item_id in enumerate(source_ids):
        comma = "," if index < len(source_ids) - 1 else ""
        lines.append(f'    "`{item_id}`"{comma}')
    lines.extend(["  ]", "}", ""])
    return "\n".join(lines)


def render_devin_agent(items) -> str:
    source_ids = ", ".join(f"`{item.item_id}`" for item in sorted(items, key=lambda i: i.item_id))
    return (
        f"{generated_header(RENDERER)}\n\n"
        "# Canonical Guidance Agent\n\n"
        "Canonical policy and procedure remain in `core/`.\n\n"
        f"Sources: {source_ids}\n\n"
        "Use generated Devin skill files as the native projections of canonical "
        "repository guidance. Do not redefine policy in this agent file.\n"
    )


def render_hooks() -> str:
    return (
        "{\n"
        '  "_generated": "<!-- Generated by adapters/devin/render.py. Do not edit directly. -->",\n'
        '  "_canonical_boundary": "Canonical policy and procedure remain in `core/`.",\n'
        '  "_note": "No executable hooks are generated yet; add hook behavior only from canonical policy and verified vendor capability data.",\n'
        '  "_source_ids": []\n'
        "}\n"
    )


def rendered_outputs() -> dict[Path, str]:
    items = canonical_items(REPO_ROOT)
    outputs = {
        AGENTS_OUTPUT: render_agents(items),
        DEVIN_CONFIG_OUTPUT: render_config(items),
        DEVIN_AGENTS_OUTPUT / "canonical-guidance" / "AGENT.md": render_devin_agent(items),
        DEVIN_HOOKS_OUTPUT: render_hooks(),
    }
    for item in sorted([candidate for candidate in items if candidate.kind == "skill"], key=lambda i: i.item_id):
        name = skill_name(item.item_id)
        skill = render_skill(item)
        outputs[AGENTS_SKILLS_OUTPUT / name / "SKILL.md"] = skill
        outputs[DEVIN_SKILLS_OUTPUT / name / "SKILL.md"] = skill
    return outputs


def check_outputs(outputs: dict[Path, str]) -> int:
    for path, rendered in sorted(outputs.items()):
        if not path.exists():
            print(f"{rel(REPO_ROOT, path)}: missing generated output", file=sys.stderr)
            return 1
        if path.read_text(encoding="utf-8") != rendered:
            print(f"{rel(REPO_ROOT, path)}: generated output is stale", file=sys.stderr)
            return 1
    print(f"{rel(REPO_ROOT, OUTPUT_ROOT)} is up to date")
    return 0


def write_outputs(outputs: dict[Path, str]) -> None:
    for generated_dir in (AGENTS_SKILLS_OUTPUT, DEVIN_SKILLS_OUTPUT, DEVIN_AGENTS_OUTPUT):
        if generated_dir.exists():
            shutil.rmtree(generated_dir)
    for path, rendered in sorted(outputs.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(rendered, encoding="utf-8")
        print(f"wrote {rel(REPO_ROOT, path)}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="check generated output freshness")
    args = parser.parse_args()
    outputs = rendered_outputs()
    if args.check:
        return check_outputs(outputs)
    write_outputs(outputs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
