"""Shared renderer helpers for vendor adapters."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any


CANONICAL_ROOTS = (
    "core/rules/atomic",
    "core/rules/languages",
    "core/rules/compositional",
    "core/skills/atomic",
    "core/skills/tools",
    "core/skills/compositional",
)


@dataclass(frozen=True)
class Item:
    path: Path
    metadata: dict[str, Any]
    body: str

    @property
    def item_id(self) -> str:
        return str(self.metadata["id"])

    @property
    def kind(self) -> str:
        return str(self.metadata["kind"])

    @property
    def summary(self) -> str:
        return str(self.metadata["summary"])


def rel(repo_root: Path, path: Path) -> str:
    return str(path.relative_to(repo_root))


def parse_scalar(raw: str) -> Any:
    value = raw.strip()
    if value == "[]":
        return []
    if value == "{}":
        return {}
    if value in {"true", "false"}:
        return value == "true"
    return value.strip('"').strip("'")


def parse_markdown(repo_root: Path, path: Path) -> Item:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0] != "---":
        raise ValueError(f"{rel(repo_root, path)}: missing frontmatter")
    closing_index = lines[1:].index("---") + 1

    metadata: dict[str, Any] = {}
    current_key: str | None = None
    for line in lines[1:closing_index]:
        if not line.strip():
            continue
        if line.startswith("  - "):
            if current_key is None:
                raise ValueError(f"{rel(repo_root, path)}: list item without key")
            metadata.setdefault(current_key, []).append(parse_scalar(line[4:]))
            continue
        key, raw_value = line.split(":", 1)
        current_key = key.strip()
        raw_value = raw_value.strip()
        metadata[current_key] = [] if not raw_value else parse_scalar(raw_value)

    body = "\n".join(lines[closing_index + 1 :]).strip()
    return Item(path=path, metadata=metadata, body=body)


def canonical_items(repo_root: Path) -> list[Item]:
    paths: list[Path] = []
    for root in CANONICAL_ROOTS:
        paths.extend(path for path in (repo_root / root).glob("*.md") if path.is_file())
    return [parse_markdown(repo_root, path) for path in sorted(paths)]


def body_without_title(body: str) -> str:
    lines = body.splitlines()
    if lines and lines[0].startswith("# "):
        return "\n".join(lines[1:]).strip()
    return body.strip()


def title(item: Item) -> str:
    first_line = item.body.splitlines()[0]
    return first_line.lstrip("# ").strip()


def skill_name(item_id: str) -> str:
    return item_id.rsplit(".", 1)[-1]


def generated_header(renderer: str) -> str:
    return f"<!-- Generated by {renderer}. Do not edit directly. -->"
