#!/usr/bin/env python3
"""Render canonical content into OpenCode-oriented generated output."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import shutil
import sys
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_ROOT = REPO_ROOT / "dist" / "opencode" / "repo-files"
AGENTS_OUTPUT = OUTPUT_ROOT / "AGENTS.md"
SKILLS_OUTPUT = OUTPUT_ROOT / ".opencode" / "skills"
CANONICAL_ROOTS = (
    REPO_ROOT / "core" / "rules" / "atomic",
    REPO_ROOT / "core" / "rules" / "languages",
    REPO_ROOT / "core" / "rules" / "compositional",
    REPO_ROOT / "core" / "skills" / "atomic",
    REPO_ROOT / "core" / "skills" / "tools",
    REPO_ROOT / "core" / "skills" / "compositional",
)


@dataclass(frozen=True)
class Item:
    path: Path
    metadata: dict[str, Any]
    body: str

    @property
    def item_id(self) -> str:
        return str(self.metadata["id"])

    @property
    def kind(self) -> str:
        return str(self.metadata["kind"])

    @property
    def summary(self) -> str:
        return str(self.metadata["summary"])


def rel(path: Path) -> str:
    return str(path.relative_to(REPO_ROOT))


def parse_scalar(raw: str) -> Any:
    value = raw.strip()
    if value == "[]":
        return []
    if value == "{}":
        return {}
    if value in {"true", "false"}:
        return value == "true"
    return value.strip('"').strip("'")


def parse_markdown(path: Path) -> Item:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0] != "---":
        raise ValueError(f"{rel(path)}: missing frontmatter")
    closing_index = lines[1:].index("---") + 1

    metadata: dict[str, Any] = {}
    current_key: str | None = None
    for line in lines[1:closing_index]:
        if not line.strip():
            continue
        if line.startswith("  - "):
            if current_key is None:
                raise ValueError(f"{rel(path)}: list item without key")
            metadata.setdefault(current_key, []).append(parse_scalar(line[4:]))
            continue
        key, raw_value = line.split(":", 1)
        current_key = key.strip()
        raw_value = raw_value.strip()
        metadata[current_key] = [] if not raw_value else parse_scalar(raw_value)

    body = "\n".join(lines[closing_index + 1 :]).strip()
    return Item(path=path, metadata=metadata, body=body)


def canonical_items() -> list[Item]:
    paths: list[Path] = []
    for root in CANONICAL_ROOTS:
        paths.extend(path for path in root.glob("*.md") if path.is_file())
    return [parse_markdown(path) for path in sorted(paths)]


def body_without_title(body: str) -> str:
    lines = body.splitlines()
    if lines and lines[0].startswith("# "):
        return "\n".join(lines[1:]).strip()
    return body.strip()


def title(item: Item) -> str:
    first_line = item.body.splitlines()[0]
    return first_line.lstrip("# ").strip()


def skill_name(item: Item) -> str:
    return item.item_id.rsplit(".", 1)[-1]


def render_agents(items: list[Item]) -> str:
    rules = sorted([item for item in items if item.kind == "rule"], key=lambda item: item.item_id)
    skills = sorted([item for item in items if item.kind == "skill"], key=lambda item: item.item_id)
    source_ids = ", ".join(f"`{item.item_id}`" for item in rules)

    lines = [
        "<!-- Generated by adapters/opencode/render.py. Do not edit directly. -->",
        "",
        "# OpenCode Instructions",
        "",
        "This generated file adapts canonical repository rules for OpenCode.",
        "Canonical policy and procedure remain in `core/`.",
        "",
        f"Sources: {source_ids}",
        "",
        "## Rules",
        "",
    ]
    for item in rules:
        lines.extend(
            [
                f"### {title(item)}",
                "",
                f"Source: `{item.item_id}`",
                "",
                body_without_title(item.body),
                "",
            ]
        )

    lines.extend(["## Skills", ""])
    for item in skills:
        name = skill_name(item)
        lines.append(f"- `{name}`: {item.summary}")
    lines.append("")
    lines.append("Generated skill files are under `.opencode/skills/<name>/SKILL.md`.")

    return "\n".join(lines).rstrip() + "\n"


def render_skill(item: Item) -> str:
    name = skill_name(item)
    return (
        "---\n"
        f"name: {name}\n"
        f"description: {item.summary}\n"
        "compatibility: opencode\n"
        "metadata:\n"
        f"  source_id: {item.item_id}\n"
        "---\n"
        "\n"
        "<!-- Generated by adapters/opencode/render.py. Do not edit directly. -->\n"
        "\n"
        f"# {title(item)}\n"
        "\n"
        "Canonical policy and procedure remain in `core/`.\n"
        "\n"
        f"Source: `{item.item_id}`\n"
        "\n"
        f"{body_without_title(item.body)}\n"
    )


def rendered_outputs() -> dict[Path, str]:
    items = canonical_items()
    outputs = {AGENTS_OUTPUT: render_agents(items)}
    for item in sorted([candidate for candidate in items if candidate.kind == "skill"], key=lambda i: i.item_id):
        outputs[SKILLS_OUTPUT / skill_name(item) / "SKILL.md"] = render_skill(item)
    return outputs


def check_outputs(outputs: dict[Path, str]) -> int:
    for path, rendered in sorted(outputs.items()):
        if not path.exists():
            print(f"{rel(path)}: missing generated output", file=sys.stderr)
            return 1
        current = path.read_text(encoding="utf-8")
        if current != rendered:
            print(f"{rel(path)}: generated output is stale", file=sys.stderr)
            return 1
    print(f"{rel(OUTPUT_ROOT)} is up to date")
    return 0


def write_outputs(outputs: dict[Path, str]) -> None:
    if SKILLS_OUTPUT.exists():
        shutil.rmtree(SKILLS_OUTPUT)
    for path, rendered in sorted(outputs.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(rendered, encoding="utf-8")
        print(f"wrote {rel(path)}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="check generated output freshness")
    args = parser.parse_args()

    outputs = rendered_outputs()
    if args.check:
        return check_outputs(outputs)

    write_outputs(outputs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
