#!/usr/bin/env python3
"""Render canonical content into Cursor-oriented generated output."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import sys
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = REPO_ROOT / "dist" / "cursor" / ".cursor" / "rules" / "canonical-guidance.mdc"
CANONICAL_ROOTS = (
    REPO_ROOT / "core" / "rules" / "atomic",
    REPO_ROOT / "core" / "rules" / "languages",
    REPO_ROOT / "core" / "rules" / "compositional",
    REPO_ROOT / "core" / "skills" / "atomic",
    REPO_ROOT / "core" / "skills" / "tools",
    REPO_ROOT / "core" / "skills" / "compositional",
)


@dataclass(frozen=True)
class Item:
    path: Path
    metadata: dict[str, Any]
    body: str

    @property
    def item_id(self) -> str:
        return str(self.metadata["id"])

    @property
    def kind(self) -> str:
        return str(self.metadata["kind"])

    @property
    def summary(self) -> str:
        return str(self.metadata["summary"])


def rel(path: Path) -> str:
    return str(path.relative_to(REPO_ROOT))


def parse_scalar(raw: str) -> Any:
    value = raw.strip()
    if value == "[]":
        return []
    if value == "{}":
        return {}
    if value in {"true", "false"}:
        return value == "true"
    return value.strip('"').strip("'")


def parse_markdown(path: Path) -> Item:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0] != "---":
        raise ValueError(f"{rel(path)}: missing frontmatter")
    closing_index = lines[1:].index("---") + 1

    metadata: dict[str, Any] = {}
    current_key: str | None = None
    for line in lines[1:closing_index]:
        if not line.strip():
            continue
        if line.startswith("  - "):
            if current_key is None:
                raise ValueError(f"{rel(path)}: list item without key")
            metadata.setdefault(current_key, []).append(parse_scalar(line[4:]))
            continue
        key, raw_value = line.split(":", 1)
        current_key = key.strip()
        raw_value = raw_value.strip()
        metadata[current_key] = [] if not raw_value else parse_scalar(raw_value)

    body = "\n".join(lines[closing_index + 1 :]).strip()
    return Item(path=path, metadata=metadata, body=body)


def canonical_items() -> list[Item]:
    paths: list[Path] = []
    for root in CANONICAL_ROOTS:
        paths.extend(path for path in root.glob("*.md") if path.is_file())
    return [parse_markdown(path) for path in sorted(paths)]


def body_without_title(body: str) -> str:
    lines = body.splitlines()
    if lines and lines[0].startswith("# "):
        return "\n".join(lines[1:]).strip()
    return body.strip()


def render_item(item: Item) -> list[str]:
    title = item.body.splitlines()[0].lstrip("# ").strip()
    return [
        f"## {title}",
        "",
        f"Source: `{item.item_id}`",
        "",
        body_without_title(item.body),
        "",
    ]


def render() -> str:
    items = sorted(canonical_items(), key=lambda item: item.item_id)
    source_ids = ", ".join(f"`{item.item_id}`" for item in items)

    lines = [
        "---",
        "description: Generated canonical repository guidance",
        "alwaysApply: true",
        "---",
        "",
        "<!-- Generated by adapters/cursor/render.py. Do not edit directly. -->",
        "",
        "# Canonical Guidance",
        "",
        "This generated Cursor rule adapts canonical repository guidance.",
        "Canonical policy and procedure remain in `core/`.",
        "",
        f"Sources: {source_ids}",
        "",
    ]
    for item in items:
        lines.extend(render_item(item))
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="check generated output freshness")
    args = parser.parse_args()

    rendered = render()
    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"{rel(OUTPUT_PATH)}: missing generated output", file=sys.stderr)
            return 1
        current = OUTPUT_PATH.read_text(encoding="utf-8")
        if current != rendered:
            print(f"{rel(OUTPUT_PATH)}: generated output is stale", file=sys.stderr)
            return 1
        print(f"{rel(OUTPUT_PATH)} is up to date")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {rel(OUTPUT_PATH)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
